"""
This type stub file was generated by pyright.
"""

import doctest
from rsa.key import PrivateKey, PublicKey, newkeys
from rsa.pkcs1 import DecryptionError, VerificationError, compute_hash, decrypt, encrypt, find_signature_hash, sign, sign_hash, verify

"""RSA module

Module for calculating large primes, and RSA encryption, decryption, signing
and verification. Includes generating public and private keys.

WARNING: this implementation does not use compression of the cleartext input to
prevent repetitions, or other common security improvements. Use with care.

"""
__author__ = ...
__date__ = ...
__version__ = ...
if __name__ == "__main__":
    ...
__all__ = ["newkeys", "encrypt", "decrypt", "sign", "verify", "PublicKey", "PrivateKey", "DecryptionError", "VerificationError", "find_signature_hash", "compute_hash", "sign_hash"]
