"""
This type stub file was generated by pyright.
"""

from pyasn1.type import univ

"""ASN.1 definitions.

Not all ASN.1-handling code use these definitions, but when it does, they should be here.
"""
class PubKeyHeader(univ.Sequence):
    componentType = ...


class OpenSSLPubKey(univ.Sequence):
    componentType = ...


class AsnPubKey(univ.Sequence):
    """ASN.1 contents of DER encoded public key:

    RSAPublicKey ::= SEQUENCE {
         modulus           INTEGER,  -- n
         publicExponent    INTEGER,  -- e
    """
    componentType = ...


