"""
This type stub file was generated by pyright.
"""

import xml.dom
from _collections_abc import dict_keys, dict_values
from _typeshed import Incomplete, ReadableBuffer, SupportsRead, SupportsWrite
from collections.abc import Iterable, Sequence
from types import TracebackType
from typing import (
    Any,
    ClassVar,
    Generic,
    Literal,
    NoReturn,
    Protocol,
    TypeAlias,
    TypeVar,
    overload,
    type_check_only,
)
from typing_extensions import Self
from xml.dom.minicompat import EmptyNodeList, NodeList
from xml.dom.xmlbuilder import DOMImplementationLS, DocumentLS
from xml.sax.xmlreader import XMLReader

_NSName: TypeAlias = tuple[str | None, str]
_NodesWithChildren: TypeAlias = DocumentFragment | Attr | Element | Document
_NodesThatAreChildren: TypeAlias = (
    CDATASection
    | Comment
    | DocumentType
    | Element
    | Notation
    | ProcessingInstruction
    | Text
)
_AttrChildren: TypeAlias = Text
_ElementChildren: TypeAlias = (
    Element | ProcessingInstruction | Comment | Text | CDATASection
)
_EntityChildren: TypeAlias = Text
_DocumentFragmentChildren: TypeAlias = (
    Element | Text | CDATASection | ProcessingInstruction | Comment | Notation
)
_DocumentChildren: TypeAlias = Comment | DocumentType | Element | ProcessingInstruction
_N = TypeVar("_N", bound=Node)
_ChildNodeVar = TypeVar("_ChildNodeVar", bound=_NodesThatAreChildren)
_ChildNodePlusFragmentVar = TypeVar(
    "_ChildNodePlusFragmentVar", bound=_NodesThatAreChildren | DocumentFragment
)
_DocumentChildrenVar = TypeVar("_DocumentChildrenVar", bound=_DocumentChildren)
_ImportableNodeVar = TypeVar(
    "_ImportableNodeVar",
    bound=DocumentFragment
    | Attr
    | Element
    | ProcessingInstruction
    | CharacterData
    | Text
    | Comment
    | CDATASection
    | Entity
    | Notation,
)

@type_check_only
class _DOMErrorHandler(Protocol):
    def handleError(self, error: Exception) -> bool: ...

@type_check_only
class _UserDataHandler(Protocol):
    def handle(
        self, operation: int, key: str, data: Any, src: Node, dst: Node
    ) -> None: ...

def parse(
    file: str | SupportsRead[ReadableBuffer | str],
    parser: XMLReader | None = ...,
    bufsize: int | None = ...,
) -> Document: ...
def parseString(
    string: str | ReadableBuffer, parser: XMLReader | None = ...
) -> Document: ...
@overload
def getDOMImplementation(features: None = ...) -> DOMImplementation: ...
@overload
def getDOMImplementation(
    features: str | Iterable[tuple[str, str | None]],
) -> DOMImplementation | None: ...

class Node(xml.dom.Node):
    parentNode: _NodesWithChildren | Entity | None
    ownerDocument: Document | None
    nextSibling: _NodesThatAreChildren | None
    previousSibling: _NodesThatAreChildren | None
    namespaceURI: str | None
    prefix: str | None
    childNodes: (
        NodeList[_DocumentFragmentChildren]
        | NodeList[_AttrChildren]
        | NodeList[_ElementChildren]
        | NodeList[_DocumentChildren]
        | NodeList[_EntityChildren]
        | EmptyNodeList
    )
    nodeType: ClassVar[Literal[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]]
    nodeName: str | None
    nodeValue: str | None
    attributes: NamedNodeMap | None
    @property
    def firstChild(self) -> _NodesThatAreChildren | None:
        """First child node, or None."""
        ...

    @property
    def lastChild(self) -> _NodesThatAreChildren | None:
        """Last child node, or None."""
        ...

    @property
    def localName(self) -> str | None:
        """Namespace-local name of this node."""
        ...

    def __bool__(self) -> Literal[True]: ...
    @overload
    def toxml(self, encoding: str, standalone: bool | None = ...) -> bytes: ...
    @overload
    def toxml(self, encoding: None = ..., standalone: bool | None = ...) -> str: ...
    @overload
    def toprettyxml(
        self,
        indent: str = ...,
        newl: str = ...,
        encoding: None = ...,
        standalone: bool | None = ...,
    ) -> str: ...
    @overload
    def toprettyxml(
        self, indent: str, newl: str, encoding: str, standalone: bool | None = ...
    ) -> bytes: ...
    @overload
    def toprettyxml(
        self,
        indent: str = ...,
        newl: str = ...,
        *,
        encoding: str,
        standalone: bool | None = ...,
    ) -> bytes: ...
    def hasChildNodes(self) -> bool: ...
    def insertBefore(
        self: _NodesWithChildren,
        newChild: _ChildNodePlusFragmentVar,
        refChild: _NodesThatAreChildren | None,
    ) -> _ChildNodePlusFragmentVar: ...
    def appendChild(
        self: _NodesWithChildren, node: _ChildNodePlusFragmentVar
    ) -> _ChildNodePlusFragmentVar: ...
    @overload
    def replaceChild(
        self: _NodesWithChildren, newChild: DocumentFragment, oldChild: _ChildNodeVar
    ) -> _ChildNodeVar | DocumentFragment: ...
    @overload
    def replaceChild(
        self: _NodesWithChildren,
        newChild: _NodesThatAreChildren,
        oldChild: _ChildNodeVar,
    ) -> _ChildNodeVar | None: ...
    def removeChild(
        self: _NodesWithChildren, oldChild: _ChildNodeVar
    ) -> _ChildNodeVar: ...
    def normalize(self: _NodesWithChildren) -> None: ...
    def cloneNode(self, deep: bool) -> Self | None: ...
    def isSupported(self, feature: str, version: str | None) -> bool: ...
    def isSameNode(self, other: Node) -> bool: ...
    def getInterface(self, feature: str) -> Self | None: ...
    def getUserData(self, key: str) -> Any | None: ...
    def setUserData(self, key: str, data: Any, handler: _UserDataHandler) -> Any: ...
    def unlink(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        et: type[BaseException] | None,
        ev: BaseException | None,
        tb: TracebackType | None,
    ) -> None: ...

_DFChildrenVar = TypeVar("_DFChildrenVar", bound=_DocumentFragmentChildren)
_DFChildrenPlusFragment = TypeVar(
    "_DFChildrenPlusFragment", bound=_DocumentFragmentChildren | DocumentFragment
)

class DocumentFragment(Node):
    nodeType: ClassVar[Literal[11]]
    nodeName: Literal["#document-fragment"]
    nodeValue: None
    attributes: None
    parentNode: None
    nextSibling: None
    previousSibling: None
    childNodes: NodeList[_DocumentFragmentChildren]
    @property
    def firstChild(self) -> _DocumentFragmentChildren | None:
        """First child node, or None."""
        ...

    @property
    def lastChild(self) -> _DocumentFragmentChildren | None:
        """Last child node, or None."""
        ...

    namespaceURI: None
    prefix: None
    @property
    def localName(self) -> None:
        """Namespace-local name of this node."""
        ...

    def __init__(self) -> None: ...
    def insertBefore(
        self,
        newChild: _DFChildrenPlusFragment,
        refChild: _DocumentFragmentChildren | None,
    ) -> _DFChildrenPlusFragment: ...
    def appendChild(self, node: _DFChildrenPlusFragment) -> _DFChildrenPlusFragment: ...
    @overload
    def replaceChild(
        self, newChild: DocumentFragment, oldChild: _DFChildrenVar
    ) -> _DFChildrenVar | DocumentFragment: ...
    @overload
    def replaceChild(
        self, newChild: _DocumentFragmentChildren, oldChild: _DFChildrenVar
    ) -> _DFChildrenVar | None: ...
    def removeChild(self, oldChild: _DFChildrenVar) -> _DFChildrenVar: ...

_AttrChildrenVar = TypeVar("_AttrChildrenVar", bound=_AttrChildren)
_AttrChildrenPlusFragment = TypeVar(
    "_AttrChildrenPlusFragment", bound=_AttrChildren | DocumentFragment
)

class Attr(Node):
    __slots__ = ...
    nodeType: ClassVar[Literal[2]]
    nodeName: str
    nodeValue: str
    attributes: None
    parentNode: None
    nextSibling: None
    previousSibling: None
    childNodes: NodeList[_AttrChildren]
    @property
    def firstChild(self) -> _AttrChildren | None:
        """First child node, or None."""
        ...

    @property
    def lastChild(self) -> _AttrChildren | None:
        """Last child node, or None."""
        ...

    namespaceURI: str | None
    prefix: str | None
    @property
    def localName(self) -> str:
        """Namespace-local name of this attribute."""
        ...

    name: str
    value: str
    specified: bool
    ownerElement: Element | None
    def __init__(
        self,
        qName: str,
        namespaceURI: str | None = ...,
        localName: str | None = ...,
        prefix: str | None = ...,
    ) -> None: ...
    def unlink(self) -> None: ...
    @property
    def isId(self) -> bool:
        """True if this attribute is an ID."""
        ...

    @property
    def schemaType(self) -> TypeInfo:
        """Schema type for this attribute."""
        ...

    def insertBefore(
        self, newChild: _AttrChildrenPlusFragment, refChild: _AttrChildren | None
    ) -> _AttrChildrenPlusFragment: ...
    def appendChild(
        self, node: _AttrChildrenPlusFragment
    ) -> _AttrChildrenPlusFragment: ...
    @overload
    def replaceChild(
        self, newChild: DocumentFragment, oldChild: _AttrChildrenVar
    ) -> _AttrChildrenVar | DocumentFragment: ...
    @overload
    def replaceChild(
        self, newChild: _AttrChildren, oldChild: _AttrChildrenVar
    ) -> _AttrChildrenVar | None: ...
    def removeChild(self, oldChild: _AttrChildrenVar) -> _AttrChildrenVar: ...

class NamedNodeMap:
    __slots__ = ...
    def __init__(
        self,
        attrs: dict[str, Attr],
        attrsNS: dict[_NSName, Attr],
        ownerElement: Element,
    ) -> None: ...
    @property
    def length(self) -> int:
        """Number of nodes in the NamedNodeMap."""
        ...

    def item(self, index: int) -> Attr | None: ...
    def items(self) -> list[tuple[str, str]]: ...
    def itemsNS(self) -> list[tuple[_NSName, str]]: ...
    def __contains__(self, key: str | _NSName) -> bool: ...
    def keys(self) -> dict_keys[str, Attr]: ...
    def keysNS(self) -> dict_keys[_NSName, Attr]: ...
    def values(self) -> dict_values[str, Attr]: ...
    def get(self, name: str, value: Attr | None = ...) -> Attr | None: ...

    __hash__: ClassVar[None]
    def __len__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: NamedNodeMap) -> bool: ...
    def __gt__(self, other: NamedNodeMap) -> bool: ...
    def __le__(self, other: NamedNodeMap) -> bool: ...
    def __lt__(self, other: NamedNodeMap) -> bool: ...
    def __getitem__(self, attname_or_tuple: _NSName | str) -> Attr: ...
    def __setitem__(self, attname: str, value: Attr | str) -> None: ...
    def getNamedItem(self, name: str) -> Attr | None: ...
    def getNamedItemNS(
        self, namespaceURI: str | None, localName: str
    ) -> Attr | None: ...
    def removeNamedItem(self, name: str) -> Attr: ...
    def removeNamedItemNS(self, namespaceURI: str | None, localName: str) -> Attr: ...
    def setNamedItem(self, node: Attr) -> Attr | None: ...
    def setNamedItemNS(self, node: Attr) -> Attr | None: ...
    def __delitem__(self, attname_or_tuple: _NSName | str) -> None: ...

AttributeList = NamedNodeMap

class TypeInfo:
    __slots__ = ...
    namespace: str | None
    name: str | None
    def __init__(self, namespace: Incomplete | None, name: str | None) -> None: ...

_ElementChildrenVar = TypeVar("_ElementChildrenVar", bound=_ElementChildren)
_ElementChildrenPlusFragment = TypeVar(
    "_ElementChildrenPlusFragment", bound=_ElementChildren | DocumentFragment
)

class Element(Node):
    __slots__ = ...
    nodeType: ClassVar[Literal[1]]
    nodeName: str
    nodeValue: None
    @property
    def attributes(self) -> NamedNodeMap:
        """NamedNodeMap of attributes on the element."""
        ...

    parentNode: Document | Element | DocumentFragment | None
    nextSibling: _DocumentChildren | _ElementChildren | _DocumentFragmentChildren | None
    previousSibling: (
        _DocumentChildren | _ElementChildren | _DocumentFragmentChildren | None
    )
    childNodes: NodeList[_ElementChildren]
    @property
    def firstChild(self) -> _ElementChildren | None:
        """First child node, or None."""
        ...

    @property
    def lastChild(self) -> _ElementChildren | None:
        """Last child node, or None."""
        ...

    namespaceURI: str | None
    prefix: str | None
    @property
    def localName(self) -> str:
        """Namespace-local name of this element."""
        ...

    schemaType: TypeInfo
    tagName: str
    def __init__(
        self,
        tagName: str,
        namespaceURI: str | None = ...,
        prefix: str | None = ...,
        localName: str | None = ...,
    ) -> None: ...
    def unlink(self) -> None: ...
    def getAttribute(self, attname: str) -> str: ...
    def getAttributeNS(self, namespaceURI: str | None, localName: str) -> str: ...
    def setAttribute(self, attname: str, value: str) -> None: ...
    def setAttributeNS(
        self, namespaceURI: str | None, qualifiedName: str, value: str
    ) -> None: ...
    def getAttributeNode(self, attrname: str) -> Attr | None: ...
    def getAttributeNodeNS(
        self, namespaceURI: str | None, localName: str
    ) -> Attr | None: ...
    def setAttributeNode(self, attr: Attr) -> Attr | None: ...

    setAttributeNodeNS = ...
    def removeAttribute(self, name: str) -> None: ...
    def removeAttributeNS(self, namespaceURI: str | None, localName: str) -> None: ...
    def removeAttributeNode(self, node: Attr) -> Attr: ...

    removeAttributeNodeNS = ...
    def hasAttribute(self, name: str) -> bool: ...
    def hasAttributeNS(self, namespaceURI: str | None, localName: str) -> bool: ...
    def getElementsByTagName(self, name: str) -> NodeList[Element]: ...
    def getElementsByTagNameNS(
        self, namespaceURI: str | None, localName: str
    ) -> NodeList[Element]: ...
    def writexml(
        self,
        writer: SupportsWrite[str],
        indent: str = ...,
        addindent: str = ...,
        newl: str = ...,
    ) -> None: ...
    def hasAttributes(self) -> bool: ...
    def setIdAttribute(self, name: str) -> None: ...
    def setIdAttributeNS(self, namespaceURI: str | None, localName: str) -> None: ...
    def setIdAttributeNode(self, idAttr: Attr) -> None: ...
    def insertBefore(
        self, newChild: _ElementChildrenPlusFragment, refChild: _ElementChildren | None
    ) -> _ElementChildrenPlusFragment: ...
    def appendChild(
        self, node: _ElementChildrenPlusFragment
    ) -> _ElementChildrenPlusFragment: ...
    @overload
    def replaceChild(
        self, newChild: DocumentFragment, oldChild: _ElementChildrenVar
    ) -> _ElementChildrenVar | DocumentFragment: ...
    @overload
    def replaceChild(
        self, newChild: _ElementChildren, oldChild: _ElementChildrenVar
    ) -> _ElementChildrenVar | None: ...
    def removeChild(self, oldChild: _ElementChildrenVar) -> _ElementChildrenVar: ...

class Childless:
    __slots__ = ...
    attributes: None
    childNodes: EmptyNodeList
    @property
    def firstChild(self) -> None: ...
    @property
    def lastChild(self) -> None: ...
    def appendChild(
        self, node: _NodesThatAreChildren | DocumentFragment
    ) -> NoReturn: ...
    def hasChildNodes(self) -> Literal[False]: ...
    def insertBefore(
        self,
        newChild: _NodesThatAreChildren | DocumentFragment,
        refChild: _NodesThatAreChildren | None,
    ) -> NoReturn: ...
    def removeChild(self, oldChild: _NodesThatAreChildren) -> NoReturn: ...
    def normalize(self) -> None: ...
    def replaceChild(
        self,
        newChild: _NodesThatAreChildren | DocumentFragment,
        oldChild: _NodesThatAreChildren,
    ) -> NoReturn: ...

class ProcessingInstruction(Childless, Node):
    __slots__ = ...
    nodeType: ClassVar[Literal[7]]
    nodeName: str
    nodeValue: str
    attributes: None
    parentNode: Document | Element | DocumentFragment | None
    nextSibling: _DocumentChildren | _ElementChildren | _DocumentFragmentChildren | None
    previousSibling: (
        _DocumentChildren | _ElementChildren | _DocumentFragmentChildren | None
    )
    childNodes: EmptyNodeList
    @property
    def firstChild(self) -> None: ...
    @property
    def lastChild(self) -> None: ...

    namespaceURI: None
    prefix: None
    @property
    def localName(self) -> None:
        """Namespace-local name of this node."""
        ...

    target: str
    data: str
    def __init__(self, target: str, data: str) -> None: ...
    def writexml(
        self,
        writer: SupportsWrite[str],
        indent: str = ...,
        addindent: str = ...,
        newl: str = ...,
    ) -> None: ...

class CharacterData(Childless, Node):
    __slots__ = ...
    nodeValue: str
    attributes: None
    childNodes: EmptyNodeList
    nextSibling: _NodesThatAreChildren | None
    previousSibling: _NodesThatAreChildren | None
    @property
    def localName(self) -> None:
        """Namespace-local name of this node."""
        ...

    ownerDocument: Document | None
    data: str
    def __init__(self) -> None: ...
    @property
    def length(self) -> int:
        """Length of the string data."""
        ...

    def __len__(self) -> int: ...
    def substringData(self, offset: int, count: int) -> str: ...
    def appendData(self, arg: str) -> None: ...
    def insertData(self, offset: int, arg: str) -> None: ...
    def deleteData(self, offset: int, count: int) -> None: ...
    def replaceData(self, offset: int, count: int, arg: str) -> None: ...

class Text(CharacterData):
    __slots__ = ...
    nodeType: ClassVar[Literal[3]]
    nodeName: Literal["#text"]
    nodeValue: str
    attributes: None
    parentNode: Attr | Element | DocumentFragment | None
    nextSibling: _DocumentFragmentChildren | _ElementChildren | _AttrChildren | None
    previousSibling: _DocumentFragmentChildren | _ElementChildren | _AttrChildren | None
    childNodes: EmptyNodeList
    @property
    def firstChild(self) -> None: ...
    @property
    def lastChild(self) -> None: ...

    namespaceURI: None
    prefix: None
    @property
    def localName(self) -> None:
        """Namespace-local name of this node."""
        ...

    data: str
    def splitText(self, offset: int) -> Self: ...
    def writexml(
        self,
        writer: SupportsWrite[str],
        indent: str = ...,
        addindent: str = ...,
        newl: str = ...,
    ) -> None: ...
    def replaceWholeText(self, content: str) -> Self | None: ...
    @property
    def isWhitespaceInElementContent(self) -> bool:
        """True iff this text node contains only whitespace and is in element content."""
        ...

    @property
    def wholeText(self) -> str:
        """The text of all logically-adjacent text nodes."""
        ...

class Comment(CharacterData):
    nodeType: ClassVar[Literal[8]]
    nodeName: Literal["#comment"]
    nodeValue: str
    attributes: None
    parentNode: Document | Element | DocumentFragment | None
    nextSibling: _DocumentChildren | _ElementChildren | _DocumentFragmentChildren | None
    previousSibling: (
        _DocumentChildren | _ElementChildren | _DocumentFragmentChildren | None
    )
    childNodes: EmptyNodeList
    @property
    def firstChild(self) -> None: ...
    @property
    def lastChild(self) -> None: ...

    namespaceURI: None
    prefix: None
    @property
    def localName(self) -> None:
        """Namespace-local name of this node."""
        ...

    def __init__(self, data: str) -> None: ...
    def writexml(
        self,
        writer: SupportsWrite[str],
        indent: str = ...,
        addindent: str = ...,
        newl: str = ...,
    ) -> None: ...

class CDATASection(Text):
    __slots__ = ...
    nodeType: ClassVar[Literal[4]]
    nodeName: Literal["#cdata-section"]
    nodeValue: str
    attributes: None
    parentNode: Element | DocumentFragment | None
    nextSibling: _DocumentFragmentChildren | _ElementChildren | None
    previousSibling: _DocumentFragmentChildren | _ElementChildren | None
    def writexml(
        self,
        writer: SupportsWrite[str],
        indent: str = ...,
        addindent: str = ...,
        newl: str = ...,
    ) -> None: ...

class ReadOnlySequentialNamedNodeMap(Generic[_N]):
    __slots__ = ...
    def __init__(self, seq: Sequence[_N] = ...) -> None: ...
    def __len__(self) -> int: ...
    def getNamedItem(self, name: str) -> _N | None: ...
    def getNamedItemNS(self, namespaceURI: str | None, localName: str) -> _N | None: ...
    def __getitem__(self, name_or_tuple: str | _NSName) -> _N | None: ...
    def item(self, index: int) -> _N | None: ...
    def removeNamedItem(self, name: str) -> NoReturn: ...
    def removeNamedItemNS(
        self, namespaceURI: str | None, localName: str
    ) -> NoReturn: ...
    def setNamedItem(self, node: Node) -> NoReturn: ...
    def setNamedItemNS(self, node: Node) -> NoReturn: ...
    @property
    def length(self) -> int:
        """Number of entries in the NamedNodeMap."""
        ...

class Identified:
    __slots__ = ...
    publicId: str | None
    systemId: str | None

class DocumentType(Identified, Childless, Node):
    nodeType: ClassVar[Literal[10]]
    nodeName: str | None
    nodeValue: None
    attributes: None
    parentNode: Document | None
    nextSibling: _DocumentChildren | None
    previousSibling: _DocumentChildren | None
    childNodes: EmptyNodeList
    @property
    def firstChild(self) -> None: ...
    @property
    def lastChild(self) -> None: ...

    namespaceURI: None
    prefix: None
    @property
    def localName(self) -> None:
        """Namespace-local name of this node."""
        ...

    name: str | None
    internalSubset: str | None
    entities: ReadOnlySequentialNamedNodeMap[Entity]
    notations: ReadOnlySequentialNamedNodeMap[Notation]
    def __init__(self, qualifiedName: str | None) -> None: ...
    def cloneNode(self, deep: bool) -> DocumentType | None: ...
    def writexml(
        self,
        writer: SupportsWrite[str],
        indent: str = ...,
        addindent: str = ...,
        newl: str = ...,
    ) -> None: ...

class Entity(Identified, Node):
    nodeType: ClassVar[Literal[6]]
    nodeName: str
    nodeValue: None
    attributes: None
    parentNode: None
    nextSibling: None
    previousSibling: None
    childNodes: NodeList[_EntityChildren]
    @property
    def firstChild(self) -> _EntityChildren | None:
        """First child node, or None."""
        ...

    @property
    def lastChild(self) -> _EntityChildren | None:
        """Last child node, or None."""
        ...

    namespaceURI: None
    prefix: None
    @property
    def localName(self) -> None:
        """Namespace-local name of this node."""
        ...

    actualEncoding: str | None
    encoding: str | None
    version: str | None
    notationName: str | None
    def __init__(
        self,
        name: str,
        publicId: str | None,
        systemId: str | None,
        notation: str | None,
    ) -> None: ...
    def appendChild(self, newChild: _EntityChildren) -> NoReturn: ...
    def insertBefore(
        self, newChild: _EntityChildren, refChild: _EntityChildren | None
    ) -> NoReturn: ...
    def removeChild(self, oldChild: _EntityChildren) -> NoReturn: ...
    def replaceChild(
        self, newChild: _EntityChildren, oldChild: _EntityChildren
    ) -> NoReturn: ...

class Notation(Identified, Childless, Node):
    nodeType: ClassVar[Literal[12]]
    nodeName: str
    nodeValue: None
    attributes: None
    parentNode: DocumentFragment | None
    nextSibling: _DocumentFragmentChildren | None
    previousSibling: _DocumentFragmentChildren | None
    childNodes: EmptyNodeList
    @property
    def firstChild(self) -> None: ...
    @property
    def lastChild(self) -> None: ...

    namespaceURI: None
    prefix: None
    @property
    def localName(self) -> None:
        """Namespace-local name of this node."""
        ...

    def __init__(
        self, name: str, publicId: str | None, systemId: str | None
    ) -> None: ...

class DOMImplementation(DOMImplementationLS):
    def hasFeature(self, feature: str, version: str | None) -> bool: ...
    def createDocument(
        self,
        namespaceURI: str | None,
        qualifiedName: str | None,
        doctype: DocumentType | None,
    ) -> Document: ...
    def createDocumentType(
        self, qualifiedName: str | None, publicId: str | None, systemId: str | None
    ) -> DocumentType: ...
    def getInterface(self, feature: str) -> Self | None: ...

class ElementInfo:
    __slots__ = ...
    tagName: str
    def __init__(self, name: str) -> None: ...
    def getAttributeType(self, aname: str) -> TypeInfo: ...
    def getAttributeTypeNS(
        self, namespaceURI: str | None, localName: str
    ) -> TypeInfo: ...
    def isElementContent(self) -> bool: ...
    def isEmpty(self) -> bool: ...
    def isId(self, aname: str) -> bool: ...
    def isIdNS(self, namespaceURI: str | None, localName: str) -> bool: ...

_DocumentChildrenPlusFragment = TypeVar(
    "_DocumentChildrenPlusFragment", bound=_DocumentChildren | DocumentFragment
)

class Document(Node, DocumentLS):
    __slots__ = ...
    nodeType: ClassVar[Literal[9]]
    nodeName: Literal["#document"]
    nodeValue: None
    attributes: None
    parentNode: None
    previousSibling: None
    nextSibling: None
    childNodes: NodeList[_DocumentChildren]
    @property
    def firstChild(self) -> _DocumentChildren | None:
        """First child node, or None."""
        ...

    @property
    def lastChild(self) -> _DocumentChildren | None:
        """Last child node, or None."""
        ...

    namespaceURI: None
    prefix: None
    @property
    def localName(self) -> None:
        """Namespace-local name of this node."""
        ...

    implementation: DOMImplementation
    actualEncoding: str | None
    encoding: str | None
    standalone: bool | None
    version: str | None
    strictErrorChecking: bool
    errorHandler: _DOMErrorHandler | None
    documentURI: str | None
    doctype: DocumentType | None
    documentElement: Element | None
    def __init__(self) -> None: ...
    def appendChild(self, node: _DocumentChildrenVar) -> _DocumentChildrenVar: ...
    def removeChild(self, oldChild: _DocumentChildrenVar) -> _DocumentChildrenVar: ...
    def unlink(self) -> None: ...
    def cloneNode(self, deep: bool) -> Document | None: ...
    def createDocumentFragment(self) -> DocumentFragment: ...
    def createElement(self, tagName: str) -> Element: ...
    def createTextNode(self, data: str) -> Text: ...
    def createCDATASection(self, data: str) -> CDATASection: ...
    def createComment(self, data: str) -> Comment: ...
    def createProcessingInstruction(
        self, target: str, data: str
    ) -> ProcessingInstruction: ...
    def createAttribute(self, qName: str) -> Attr: ...
    def createElementNS(
        self, namespaceURI: str | None, qualifiedName: str
    ) -> Element: ...
    def createAttributeNS(
        self, namespaceURI: str | None, qualifiedName: str
    ) -> Attr: ...
    def getElementById(self, id: str) -> Element | None: ...
    def getElementsByTagName(self, name: str) -> NodeList[Element]: ...
    def getElementsByTagNameNS(
        self, namespaceURI: str | None, localName: str
    ) -> NodeList[Element]: ...
    def isSupported(self, feature: str, version: str | None) -> bool: ...
    def importNode(
        self, node: _ImportableNodeVar, deep: bool
    ) -> _ImportableNodeVar: ...
    def writexml(
        self,
        writer: SupportsWrite[str],
        indent: str = ...,
        addindent: str = ...,
        newl: str = ...,
        encoding: str | None = ...,
        standalone: bool | None = ...,
    ) -> None: ...
    @overload
    def renameNode(self, n: Element, namespaceURI: str, name: str) -> Element: ...
    @overload
    def renameNode(self, n: Attr, namespaceURI: str, name: str) -> Attr: ...
    @overload
    def renameNode(
        self, n: Element | Attr, namespaceURI: str, name: str
    ) -> Element | Attr: ...
    def insertBefore(
        self,
        newChild: _DocumentChildrenPlusFragment,
        refChild: _DocumentChildren | None,
    ) -> _DocumentChildrenPlusFragment: ...
    @overload
    def replaceChild(
        self, newChild: DocumentFragment, oldChild: _DocumentChildrenVar
    ) -> _DocumentChildrenVar | DocumentFragment: ...
    @overload
    def replaceChild(
        self, newChild: _DocumentChildren, oldChild: _DocumentChildrenVar
    ) -> _DocumentChildrenVar | None: ...
